### ISSUE TITLE
Style the choose file button

### ISSUE THREAD

**Issue by Explosion-Scratch** [JeffaloBob/noted#27]
No offense but it looks sorta bad lol:
![image](https://user-images.githubusercontent.com/61319150/94922169-521e3080-047f-11eb-9173-27a622a87329.png)

Maybe add this to it:
``` css
.file-button {
	background-color: blue;
	/*Or whatever the color you want is lol */
	padding: 6px;
	border-radius: 5px;
	color: white;
	transition: 0.4s color, 0.4s background-color, 0.4s box-shadow;
	border: 1px solid blue;
}

.file-button:hover {
	border: 1px solid blue;
	background-color: white;
	color: #101010;
	box-shadow: 0 3px 5px 1px rgba(0, 0, 0, .2);
}

.file-button:active {
	transform: translate(0, 2px);
}

.file-button:focus {
	outline: none;
}
```
